### ISSUE TITLE
Improvement error message for VSCode Extension

### ISSUE THREAD

**Issue by tanzaku** [future-architect/uroborosql-fmt#37]
The VSCode extension uses the showErrorMessage API to display error messages, but this API does not allow line breaks, so the display is corrupted.

**Comment by ppputtyo** [comment]
現在はフォーマットエラーが発生した場合は`showErrorMessage`と`Output`に出力を行っていますが、`Output`だけに出力するように変更するのはいかがでしょうか。
`Output`の出力は崩れずに表示できていることを確認済みです。
出力例
![スクリーンショット 2023-11-04 12 43 10](https://github.com/future-architect/uroborosql-fmt/assets/52311998/b0097bc7-3e98-4e62-8f20-86fc117231a9)


例えばPrrettierなども同様にフォーマットエラーが発生した場合は`Output`のみに出力をおこなっています。
`Output`の出力
![image](https://github.com/future-architect/uroborosql-fmt/assets/52311998/9b12199b-e2c5-43f2-afbd-51fbf6d94f39)

**Comment by tanzaku** [comment]
単に `showErrorMessage` を出さないだけだと、エラーが起きたことに気づきづらいかなという点が気になっています。

Prettierはステータスバーで拡張の状態を表示しており、エラー発生時にはステータスバーを赤くし、クリックするとOuputを開くようになっているらしいと識者に聞きました。uroborosql-fmtでも同様の方法で通知できたらベストかなと思いました。
ステータスバーでの表示が難しかったら、「A formatting error has occurred. See Output for details.」のようなメッセージを出すことで、最低限エラーが発生したことはわかるようにした方がいいかなと思います。

いかがでしょうか。

**Comment by tanzaku** [comment]
StatusBarItemクラスのcommandプロパティで、ステータスバークリック時に実行するコマンドを指定できるみたいですね
https://code.visualstudio.com/api/references/vscode-api#StatusBarItem

**Comment by ppputtyo** [comment]
https://github.com/future-architect/vscode-uroborosql-fmt/pull/53

修正が完了したためCloseします。
