### ISSUE TITLE
タブ表示幅を2byteにしていると、WHERE句に複数の条件がある際のフォーマットが規約通りでない。

### ISSUE THREAD

**Issue by taichi** [future-architect/uroborosql-fmt#44]
[規約](https://future-architect.github.io/coding-standards/documents/forSQL/SQL%E3%82%B3%E3%83%BC%E3%83%87%E3%82%A3%E3%83%B3%E3%82%B0%E8%A6%8F%E7%B4%84%EF%BC%88PostgreSQL%EF%BC%89.html#sql-%E6%96%87%E3%81%AE%E6%95%B4%E5%BD%A2)によると、以下のようにフォーマットされることが期待されます。

<img width="325" alt="image" src="https://github.com/future-architect/uroborosql-fmt/assets/66100/5a0237a6-938b-4bb7-9b06-d0eb7f03b197">

しかし、実際にはtabSizeを2にしても以下のようにフォーマットされるのみです。

<img width="334" alt="image" src="https://github.com/future-architect/uroborosql-fmt/assets/66100/a9529730-0f0a-4479-8795-a63ef6b79c30">

7行目の先頭に付与されているタブ数が一つ不足していると思われます。

**Comment by tanzaku** [comment]
issue起票ありがとうございます。
本issueの不具合を修正し、期待通りフォーマットされるようになったためcloseします。
